services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    container_name: task_manager_db
    ports:
      - '5433:5432'

  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'make dev'
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    container_name: task_manager
    volumes:
      - .:/usr/local/src/task_manager
    ports:
      - '8080:8080'
    depends_on:
      - db

volumes:
  postgres_volume: