# Generated by Django 4.2.2 on 2024-04-23 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserFullName",
        ),
    ]
