# Generated by Django 5.0.3 on 2024-04-18 16:35

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0002_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFullName",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
