# Generated by Django 5.0.4 on 2024-04-21 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("labels", "0001_initial"),
        ("statuses", "0001_initial"),
        ("tasks", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="author",
                to="users.userfullname",
                verbose_name="Author",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="executor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="executor",
                to="users.userfullname",
                verbose_name="Executor",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="statuses.status",
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="tasklabelthrough",
            name="label",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="labels.label"
            ),
        ),
        migrations.AddField(
            model_name="tasklabelthrough",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tasks.task"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                through="tasks.TaskLabelThrough",
                to="labels.label",
                verbose_name="Labels",
            ),
        ),
    ]
