# Generated by Django 5.0.4 on 2024-04-14 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labels", "0001_initial"),
        ("tasks", "0002_alter_task_executor_tasklabelthrough_task_label"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="executor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="executor",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Executor",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="label",
            field=models.ManyToManyField(
                blank=True,
                through="tasks.TaskLabelThrough",
                to="labels.label",
                verbose_name="Label",
            ),
        ),
    ]
